### ISSUE TITLE
Feat -> Jobs Landing Page -> Desktop and Mobile Design Implementation -> Static Page + job-card component

### ISSUE THREAD

**Issue by ekas** [jslovers/jslovers-official-website#10]
[Mobile Design](https://www.figma.com/file/Vic6wWFsQVt0YlR5jCkoT6/js-lovers-designfile-(Copy)?type=design&node-id=291%3A3140&mode=design&t=5J3bmQZdbYHrsnMr-1)
[Desktop Design](https://www.figma.com/file/Vic6wWFsQVt0YlR5jCkoT6/js-lovers-designfile-(Copy)?type=design&node-id=191%3A247&mode=design&t=5J3bmQZdbYHrsnMr-1)

**Comment by brindashree** [comment]
Hi, i'd like to work on this.
