### ISSUE TITLE
Feat -> Speakers Page -> Desktop & Mobile Design Implementation with Speakers Carousel Component -> Static Page

### ISSUE THREAD

**Issue by ekas** [jslovers/jslovers-official-website#17]
[Desktop Design](https://www.figma.com/file/Vic6wWFsQVt0YlR5jCkoT6/js-lovers-designfile-(Copy)?type=design&node-id=191%3A534&mode=design&t=5J3bmQZdbYHrsnMr-1)

[Mobile Design](https://www.figma.com/file/Vic6wWFsQVt0YlR5jCkoT6/js-lovers-designfile-(Copy)?type=design&node-id=315%3A197&mode=design&t=5J3bmQZdbYHrsnMr-1)

**Comment by aaveggupta** [comment]
can i pick this up? @ekas

**Comment by ekas** [comment]
> can i pick this up? @ekas Also one thing i observed Mobile and Desktop are not very much sync with each other! Mobile desgn has one section extra compared to desktop one

Please go ahead. For the missing section, while developing please include that in as well in desktop mode. Thanks

**Comment by drashish77** [comment]
Hey, ekas is this page complete?

**Comment by singhlify** [comment]
@ekas Hi, can I pick this up?

**Comment by ekas** [comment]
@singhlify Go for it.
