### ISSUE TITLE
Feat -> About Us Page -> Desktop and Mobile Design Implementation - Static Page

### ISSUE THREAD

**Issue by ekas** [jslovers/jslovers-official-website#19]
[Desktop Design - 1](https://www.figma.com/file/Vic6wWFsQVt0YlR5jCkoT6/js-lovers-designfile-(Copy)?type=design&node-id=191%3A1697&mode=design&t=5J3bmQZdbYHrsnMr-1)

[Desktop Design - 2](https://www.figma.com/file/Vic6wWFsQVt0YlR5jCkoT6/js-lovers-designfile-(Copy)?type=design&node-id=191%3A862&mode=design&t=5J3bmQZdbYHrsnMr-1)

[Mobile Design - 1](https://www.figma.com/file/Vic6wWFsQVt0YlR5jCkoT6/js-lovers-designfile-(Copy)?type=design&node-id=317%3A1046&mode=design&t=5J3bmQZdbYHrsnMr-1)

[Mobile Design - 2](https://www.figma.com/file/Vic6wWFsQVt0YlR5jCkoT6/js-lovers-designfile-(Copy)?type=design&node-id=317%3A1046&mode=design&t=5J3bmQZdbYHrsnMr-1)

**Comment by ruhankhandakar** [comment]
Also wants to this.

**Comment by ekas** [comment]
> Also wants to this.

Go for it.

**Comment by singhlify** [comment]
@ekas Can you please assign this to me?
