### ISSUE TITLE
Chore -> Docs to Raise an Issue

### ISSUE THREAD

**Issue by ekas** [jslovers/jslovers-official-website#24]

**Comment by gamedevCloudy** [comment]
I would like to Contribute.

**Comment by ekas** [comment]
@gamedevCloudy Any update on this?

**Comment by gamedevCloudy** [comment]
Sorry, was ill. Will complete by Friday.

**Comment by gamedevCloudy** [comment]
https://github.com/jslovers/jslovers-official-website/pull/32
