### ISSUE TITLE
Chore -> Add Cypress Automation Test Framework and update docs

### ISSUE THREAD

**Issue by ekas** [jslovers/jslovers-official-website#26]

**Comment by Neha** [comment]
I am thinking to have cypress as E2E automation - thoughts @ekas  @atishaybaid

**Comment by ekas** [comment]
Yes, I am good with Cypress or Playwright.

**Comment by Neha** [comment]
@ekas I have updated the title of the ticket. E2E automation will be done once the code is ready.

For now, we should have unit, and integration test-cases in the place and later we will add E2E

**Comment by saurabhsubham113** [comment]
Hi @Neha ,

I have added the initial setup and one e2e test case for the about page.
I have attached the PR below,
https://github.com/jslovers/jslovers-official-website/pull/94
