### ISSUE TITLE
S should be capital in JsLover*

### ISSUE THREAD

**Issue by Neha** [jslovers/jslovers-official-website#52]
**Describe the bug**
On homepage, S should be capital in **JsLover**, in the section - wanna be JsLover

**To Reproduce**
1. Go to homepage
2. Scroll down to section - wanna be a JsLovers
4. check text "JsLovers"

**Expected behavior**
It should be JSLovers ; S should be capital

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ramnaresh8** [comment]
I want to solve this, can you share a screenshot or the link of the file where S needs to be updated?
