### ISSUE TITLE
Homepage should not be named marketing 

### ISSUE THREAD

**Issue by Neha** [jslovers/jslovers-official-website#59]
**Describe the bug**
Currently we have name the _homepage_ or _index_ _(marketing)_ , the name is not reflecting the page content, It should name home

**To Reproduce**
1. Go to code
2. Click on 'app' folder and check the '(marketing)'

**Expected behavior**
It should be home page or something that reflect the content of the page

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DivyanshVinayak23** [comment]
Hi can I work on this?

**Comment by Neha** [comment]
Hey @DivyanshVinayak23  could you please share the expected timeline?

**Comment by DivyanshVinayak23** [comment]
> Hey @DivyanshVinayak23 could you please share the expected timeline?

could you please further explain the issue? I am having a hard time understanding

**Comment by Neha** [comment]
> > Hey @DivyanshVinayak23 could you please share the expected timeline?
> 
> could you please further explain the issue? I am having a hard time understanding

Here are the steps and expected behaviour:

**Steps to reproduce the behavior:**

1. Go to code
2. Click on 'app' folder and check the '(marketing)'

**Expected behavior**
1. It should be home page or something that reflect the content of the page

This is a quick fix. So, over the weekend you can fix would be great, Thanks
