### ISSUE TITLE
Feat -> Landing Page -> Desktop and Mobile Design Implementation -> Static Page

### ISSUE THREAD

**Issue by ekas** [jslovers/jslovers-official-website#6]
[Mobile Design](https://www.figma.com/file/Vic6wWFsQVt0YlR5jCkoT6/js-lovers-designfile-(Copy)?type=design&node-id=286%3A197&mode=design&t=RS1OeLiLW2MHG7Yp-1)
[Desktop Design](https://www.figma.com/file/Vic6wWFsQVt0YlR5jCkoT6/js-lovers-designfile-(Copy)?type=design&node-id=215%3A15062&mode=design&t=RS1OeLiLW2MHG7Yp-1)

**Comment by ra-kesh** [comment]
I would like to work on this

**Comment by ekas** [comment]
> I would like to work on this 

Yes please go for it.
