### ISSUE TITLE
Code: need to rename all page from XPageIndex to page

### ISSUE THREAD

**Issue by Neha** [jslovers/jslovers-official-website#62]
**Describe the bug**
Currently, in our code we have all pages with function name `aboutPageIndex` this is not required. We can simply have `page` or if required then `aboutPage`

**To Reproduce**
1. Go to code
2. Click on app folder
3. Scroll down to any folder
4. Open page.tsx and see the name of the function

**Expected behavior**
Currently, in our code we have all pages with function name `aboutPageIndex` this is not required. We can simply have `page` or if required then `aboutPage`

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vignesh-murugan-dev** [comment]
Hi Neha, 

Can I work on this?
