### ISSUE TITLE
types needs to be optimized

### ISSUE THREAD

**Issue by Neha** [jslovers/jslovers-official-website#70]
**Describe the bug**
Currently types in project have following issues:

1. interface naming convention are not clean. Eg: FooterData can be just Footer
2. types and interfaces are spread across type file and component file. Interfaces if (are) reusable and should be in a separate file. types should be in the component. Basically one clear approach should be there

**To Reproduce**
1. Go to project code
3. Click on types

**Expected behavior**
A clear:
1. naming convention
2. rules around where to keep types and interfaces

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by greykoalacode** [comment]
Hey @Neha I will try solving this issue. Reading your comment, just wanted to confirm Is it fine to have types in Component files & interfaces in a separate file. Do you have any more suggestion ? 
I will raise a PR once I'm done with it. Thank you :)

**Comment by Neha** [comment]
Hello @greykoalacode , if the interfaces are reusable then they should be in a separate file.  Otherwise it would be types in the component file.

Also, when we are saying "reusable" then the names are important. So, that it would be easier to use and understand.

A few places types, and interfaces are names as FooterData, AboutData. We don't need "data" or "PurposeCards" or "navItem" - do we need to add "item" with types? . 

This is not a clean naming way.

I am open for suggestions. Can you please suggest a scalable , readable, and maintable way of adding types?

**Comment by greykoalacode** [comment]
I just went by this: https://docs.aws.amazon.com/prescriptive-guidance/latest/best-practices-cdk-typescript-iac/typescript-best-practices.html & as you suggested, I also feel that the Naming can be better. For eg, Footer instead of "FooterData". FooterProps instead of FooterData. Let me know if you've any ideas :)
Actually I'm not that fluent in dealing with typescript applications so I am not aware of much best practices. I'll try to keep it simple and understandable.

**Comment by Sachin70** [comment]
Hello @Neha, If This Types issue is still open the I can contribute to optimise the types issue.

**Comment by Neha** [comment]
@Sachin70 and @greykoalacode I would suggest you both can discuss and divide the tasks. wyt? Let me know.

**Comment by greykoalacode** [comment]
As I can see, we can divide tasks as naming convention & placing them accordingly (in a separate file / within component). I could start with naming convention on a feature branch @Sachin70  could take it over and see about placing them / migrating them if needed. We can raise a PR as we feel sure about it. Is that fine?

**Comment by greykoalacode** [comment]
Hey @Neha , I created a PR but I couldn't link it to this issue. Can you have a look ?
https://github.com/jslovers/jslovers-official-website/pull/93
It's my first time trying to contribute so maybe I'm missing the point of how to link issue to a PR/branch. Thank you
