### ISSUE TITLE
fix alt tags of speaker cards

### ISSUE THREAD

**Issue by Neha** [jslovers/jslovers-official-website#78]
**Describe the bug**
alt tags of speaker cards are hardcoded

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to components
2. Click on speaker components
3. check alt tags 

**Expected behavior**
alt tags either be dynamic or if presentational only then do not show the alt tags

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by akshat99812** [comment]
I would like to contribute on this. Can you assign me this issue?

**Comment by Neha** [comment]
> I would like to contribute on this. Can you assign me this issue?

Thank you. My suggestion please close the existing issue you have picked . Once that is close will assign a new issue.
