### ISSUE TITLE
update favicon for JSLovers

### ISSUE THREAD

**Issue by Neha** [jslovers/jslovers-official-website#82]
**Is your feature request related to a problem? Please describe.**
create and update the favicon of the website

**Describe the solution you'd like**
create and update the favicon of the website

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Vrukshali-26** [comment]
I can work on this

**Comment by Neha** [comment]
@Vrukshali-26 please share SLA for this task.
