### ISSUE TITLE
Module not found: Can't resolve error

### ISSUE THREAD

**Issue by SureshKuchana** [jslovers/jslovers-official-website#86]
**Describe the bug**
Currently if i ran the application, throwing the `Module not found: Can't resolve '@/components/Navigation/MainNav' error

**To Reproduce**
1. clone the repo `https://github.com/your-username/jslovers-official-website.git`
2. Install the dependencies `npm i or yarn`
3. and run the application `npm run dev or yarn dev`
4. See error `Module not found: Can't resolve '@/components/Navigation/MainNav'`

**Expected behavior**
Application should run without any fail.

**Screenshots**
![image](https://github.com/jslovers/jslovers-official-website/assets/29767625/252a72a4-cf41-4bda-87d4-63fdedceaf41)

![image](https://github.com/jslovers/jslovers-official-website/assets/29767625/cb2b42bb-678d-49c6-ab55-9da479b0d097)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Brave & Chrome
 - Version: Brave (1.67.119) & Chrome (126.0.6478.114)

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by SureshKuchana** [comment]
@Neha Will create a PR

**Comment by Neha** [comment]
The fix is navigation folder should be rename to uppercase N -> Navigation.

I took the dev pull but not able to see this gap in my local. Would you like to go ahead and push from your end this change?

**Comment by SureshKuchana** [comment]
@Neha created PR https://github.com/jslovers/jslovers-official-website/pull/88
